POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Cur"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/85a6c938-78b7-4c44-8c65-0debaaf9ebd2